-- 035_livebook_image_library.sql
-- CEO-163 — Livebook image library: schema foundation
--
-- Replaces per-publish image generation with a curated, reusable library.
-- A book opts in at publish time, picks a visual style, pays 1000 credits,
-- and the worker matches each paragraph to the best-fit image in that style
-- via vector similarity search over Claude-Vision-generated captions.
--
-- This migration: extensions, tables, indexes, RLS enable.
-- Migration 036 ships the RLS policies (split per CEO-149 lesson that
-- CREATE POLICY silently drops when batched with CREATE TABLE in the same
-- apply_migration call).

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- livebook_styles — the curated visual style catalogue
-- ============================================================================
-- Each book picks ONE style at enrollment. All paragraph→image matching for
-- that book is then constrained to images tagged with this style. This is
-- what guarantees aesthetic consistency within a book — no mixing watercolor
-- and cinematic photorealism in the same livebook.

CREATE TABLE IF NOT EXISTS livebook_styles (
  slug                  text PRIMARY KEY,
  display_name          text NOT NULL,
  description           text NOT NULL,
  sample_thumbnail_urls text[] NOT NULL DEFAULT '{}',
  price_credits         integer NOT NULL DEFAULT 1000 CHECK (price_credits >= 0),
  recommended_genres    text[] NOT NULL DEFAULT '{}',
  is_active             boolean NOT NULL DEFAULT true,
  display_order         integer NOT NULL DEFAULT 0,
  library_size          integer NOT NULL DEFAULT 0,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS livebook_styles_active_order_idx
  ON livebook_styles (is_active, display_order)
  WHERE is_active = true;

COMMENT ON TABLE livebook_styles IS 'CEO-163: Curated visual style catalogue for the Livebook image library. Each style has its own pool of pre-generated images. library_size is denormalised for fast UI rendering and is recalculated nightly.';

-- ============================================================================
-- livebook_image_library — the actual image pool, embedded for ANN search
-- ============================================================================
-- Embedding dimension is 1024 to match Voyage-3 (Anthropic's recommended
-- embedding model post-acquisition). Captions are generated by Claude Vision
-- at ingestion time — not the prompts the image was generated from. The
-- caption describes what is actually visible, in language that matches the
-- prose the worker will be embedding.

CREATE TABLE IF NOT EXISTS livebook_image_library (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  style_slug        text NOT NULL REFERENCES livebook_styles(slug) ON DELETE RESTRICT,
  image_url         text NOT NULL,
  thumbnail_url     text,
  aspect_ratio      text NOT NULL DEFAULT '16:9' CHECK (aspect_ratio IN ('16:9','9:16','1:1','4:3','3:4')),
  caption           text NOT NULL,
  caption_short     text,
  tags              text[] NOT NULL DEFAULT '{}',
  content_genres    text[] NOT NULL DEFAULT '{}',
  era               text,
  mood              text,
  embedding         vector(1024),
  source_model      text NOT NULL DEFAULT 'flux-pro-1.1',
  source_prompt     text,
  generation_cost_cents integer,
  width_px          integer,
  height_px         integer,
  file_size_bytes   integer,
  use_count         integer NOT NULL DEFAULT 0,
  last_used_at      timestamptz,
  thumbs_up_count   integer NOT NULL DEFAULT 0,
  thumbs_down_count integer NOT NULL DEFAULT 0,
  is_active         boolean NOT NULL DEFAULT true,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

-- HNSW index for cosine similarity search. m=16/ef_construction=64 are the
-- pgvector defaults that give a good recall/build-time tradeoff for libraries
-- under ~100k vectors. Filtered scans by style_slug stay fast because the
-- style filter cuts the candidate set ~10x before the vector scan.
CREATE INDEX IF NOT EXISTS livebook_image_library_embedding_idx
  ON livebook_image_library
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS livebook_image_library_style_active_idx
  ON livebook_image_library (style_slug, is_active)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS livebook_image_library_tags_gin_idx
  ON livebook_image_library USING gin (tags);

CREATE INDEX IF NOT EXISTS livebook_image_library_genres_gin_idx
  ON livebook_image_library USING gin (content_genres);

COMMENT ON TABLE livebook_image_library IS 'CEO-163: The image pool. Captions are Claude-Vision-generated (NOT the source prompt) so they describe what is visible in language matching prose. Embedding is Voyage-3 (1024-dim).';
COMMENT ON COLUMN livebook_image_library.use_count IS 'Incremented each time this image is matched into a generated livebook. Used for round-robin diversity scoring to avoid the same hero image appearing in 50 books.';

-- ============================================================================
-- livebook_generation_jobs — async job queue, replaces per-publish trigger
-- ============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'livebook_job_status') THEN
    CREATE TYPE livebook_job_status AS ENUM (
      'queued',
      'running',
      'succeeded',
      'failed',
      'cancelled'
    );
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS livebook_generation_jobs (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  listing_id          uuid NOT NULL,
  style_slug          text NOT NULL REFERENCES livebook_styles(slug) ON DELETE RESTRICT,
  status              livebook_job_status NOT NULL DEFAULT 'queued',
  progress_percent    integer NOT NULL DEFAULT 0 CHECK (progress_percent BETWEEN 0 AND 100),
  status_message      text,
  paragraphs_total    integer,
  paragraphs_matched  integer NOT NULL DEFAULT 0,
  paragraphs_skipped  integer NOT NULL DEFAULT 0,
  match_log           jsonb NOT NULL DEFAULT '[]'::jsonb,
  credits_charged     integer NOT NULL DEFAULT 1000,
  charged_to_user_id  uuid NOT NULL,
  error_text          text,
  retry_count         integer NOT NULL DEFAULT 0,
  queued_at           timestamptz NOT NULL DEFAULT now(),
  started_at          timestamptz,
  completed_at        timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS livebook_jobs_listing_idx
  ON livebook_generation_jobs (listing_id, queued_at DESC);

CREATE INDEX IF NOT EXISTS livebook_jobs_status_queued_idx
  ON livebook_generation_jobs (status, queued_at)
  WHERE status IN ('queued','running');

COMMENT ON TABLE livebook_generation_jobs IS 'CEO-163: One row per livebook generation attempt. match_log is a jsonb array of {paragraph_idx, image_id, similarity_score, fallback_reason} per matched paragraph for debugging and quality flywheel.';

-- ============================================================================
-- store_listings — Livebook enrollment columns
-- ============================================================================
-- We add new columns rather than reusing the existing livebook_* columns
-- (which are TTS-audio-related and stay for the audio mode of the livebook).
-- The new columns describe the IMAGE side of the v3 livebook.

ALTER TABLE store_listings
  ADD COLUMN IF NOT EXISTS livebook_enrolled        boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS livebook_style           text REFERENCES livebook_styles(slug) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS livebook_image_status    text NOT NULL DEFAULT 'not_enrolled'
    CHECK (livebook_image_status IN ('not_enrolled','queued','generating','ready','failed')),
  ADD COLUMN IF NOT EXISTS livebook_image_progress  integer NOT NULL DEFAULT 0
    CHECK (livebook_image_progress BETWEEN 0 AND 100),
  ADD COLUMN IF NOT EXISTS livebook_image_map       jsonb,
  ADD COLUMN IF NOT EXISTS livebook_enrolled_at     timestamptz,
  ADD COLUMN IF NOT EXISTS livebook_image_ready_at  timestamptz;

CREATE INDEX IF NOT EXISTS store_listings_livebook_enrolled_idx
  ON store_listings (livebook_enrolled, livebook_image_status)
  WHERE livebook_enrolled = true;

COMMENT ON COLUMN store_listings.livebook_image_map IS 'CEO-163: Resolved paragraph→image_url map for fast reader rendering. Shape: [{paragraph_idx:int, image_id:uuid, image_url:text, thumbnail_url:text, similarity:float}, ...]. Null until status=ready.';

-- ============================================================================
-- updated_at triggers
-- ============================================================================

CREATE OR REPLACE FUNCTION livebook_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END$$;

DROP TRIGGER IF EXISTS livebook_styles_updated_at ON livebook_styles;
CREATE TRIGGER livebook_styles_updated_at
  BEFORE UPDATE ON livebook_styles
  FOR EACH ROW EXECUTE FUNCTION livebook_set_updated_at();

DROP TRIGGER IF EXISTS livebook_image_library_updated_at ON livebook_image_library;
CREATE TRIGGER livebook_image_library_updated_at
  BEFORE UPDATE ON livebook_image_library
  FOR EACH ROW EXECUTE FUNCTION livebook_set_updated_at();

DROP TRIGGER IF EXISTS livebook_generation_jobs_updated_at ON livebook_generation_jobs;
CREATE TRIGGER livebook_generation_jobs_updated_at
  BEFORE UPDATE ON livebook_generation_jobs
  FOR EACH ROW EXECUTE FUNCTION livebook_set_updated_at();

-- ============================================================================
-- RLS enable (policies ship in 036_livebook_image_library_policies.sql)
-- ============================================================================

ALTER TABLE livebook_styles            ENABLE ROW LEVEL SECURITY;
ALTER TABLE livebook_image_library     ENABLE ROW LEVEL SECURITY;
ALTER TABLE livebook_generation_jobs   ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- Seed the two Phase-0 styles
-- ============================================================================

INSERT INTO livebook_styles (slug, display_name, description, recommended_genres, display_order)
VALUES
  ('vintage_painting',
   'Vintage Painting',
   'Hand-painted oil-on-canvas style evoking 1940s–1950s European illustration. Warm palettes, romantic atmosphere, Mediterranean and Parisian settings. Ideal for romance, literary fiction, historical, and memoir.',
   ARRAY['romance','historical','literary','memoir','travel'],
   10),
  ('cinematic_photoreal',
   'Cinematic Photorealistic',
   'High-detail photoreal cinematography with dramatic lighting and depth. Suited to thrillers, contemporary fiction, biography, and historical narratives where realism heightens immersion.',
   ARRAY['thriller','contemporary','biography','historical','non-fiction'],
   20)
ON CONFLICT (slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  recommended_genres = EXCLUDED.recommended_genres,
  display_order = EXCLUDED.display_order;
