import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';
import { createClient } from '@/lib/supabase/server';
import { ensurePublishingMetadata } from '@/lib/publishing/metadata';
import { getKitBuilder } from '@/lib/publishing/publish-kits';

export const runtime = 'nodejs';
export const maxDuration = 60;

/**
 * GET /api/publishing/bundle?projectId=<uuid>&platformSlug=<slug>
 *
 * Packages the author's publish kit into a single ZIP download:
 *   - manuscript.docx   (always, minimal OOXML)
 *   - cover.jpg         (if front_cover_url present)
 *   - metadata.txt      (copy-paste block: title, description, keywords, etc.)
 *   - README.txt        (the step-by-step walkthrough + deep link)
 *
 * EPUB generation is not included in this iteration — KDP/IngramSpark/B&N
 * accept DOCX upload with auto-conversion, so DOCX + cover + metadata is
 * enough to complete the manual publish. EPUB can be added as a follow-up.
 */
export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const url = new URL(request.url);
  const projectId = url.searchParams.get('projectId');
  const platformSlug = url.searchParams.get('platformSlug');
  if (!projectId || !platformSlug) {
    return NextResponse.json({ error: 'projectId and platformSlug required' }, { status: 400 });
  }

  const { data: platform } = await supabase
    .from('publishing_platforms')
    .select('id, name, slug, publish_tier')
    .eq('slug', platformSlug)
    .single();
  if (!platform) return NextResponse.json({ error: 'Platform not found' }, { status: 404 });
  if (platform.publish_tier !== 'guided_pdf') {
    return NextResponse.json({ error: 'Bundles are only for guided publish platforms' }, { status: 400 });
  }

  const { data: project } = await supabase
    .from('projects')
    .select('id, title, description, user_id')
    .eq('id', projectId)
    .eq('user_id', user.id)
    .single();
  if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 });

  const { data: chapters } = await supabase
    .from('chapters')
    .select('title, content, order_index')
    .eq('project_id', projectId)
    .eq('status', 'complete')
    .order('order_index');

  if (!chapters || chapters.length === 0) {
    return NextResponse.json({ error: 'No completed chapters to bundle' }, { status: 400 });
  }

  const meta = await ensurePublishingMetadata(supabase, projectId, user.id);
  if (!meta) return NextResponse.json({ error: 'Could not load publishing metadata' }, { status: 500 });

  const builder = getKitBuilder(platformSlug);
  if (!builder) return NextResponse.json({ error: 'No kit builder for this platform' }, { status: 404 });
  const kit = builder(meta);

  const { data: session } = await supabase
    .from('interview_sessions')
    .select('front_cover_url')
    .eq('project_id', projectId)
    .eq('user_id', user.id)
    .maybeSingle();
  const coverUrl = session?.front_cover_url as string | null;

  const bundle = new JSZip();

  // 1. manuscript.docx
  bundle.file('manuscript.docx', await buildSimpleDocx(meta.title, meta.author_name, chapters));

  // 2. cover.jpg (best-effort — non-fatal if the image fetch fails)
  if (coverUrl) {
    try {
      const resp = await fetch(coverUrl);
      if (resp.ok) {
        const buf = Buffer.from(await resp.arrayBuffer());
        bundle.file('cover.jpg', buf);
      }
    } catch {
      // ignore
    }
  }

  // 3. metadata.txt
  const metaLines: string[] = [
    `${kit.platformName.toUpperCase()} — PUBLISH METADATA`,
    `Generated by Penworth · ${new Date().toISOString().slice(0, 10)}`,
    '',
    ...kit.fields
      .filter((f) => f.value)
      .map((f) => `${f.label.toUpperCase()}${f.note ? ` (${f.note})` : ''}:\n${f.value}\n`),
  ];
  bundle.file('metadata.txt', metaLines.join('\n'));

  // 4. README.txt
  const readmeLines: string[] = [
    `PENWORTH PUBLISH KIT — ${kit.platformName}`,
    `Estimated time: ${kit.estimatedMinutes} minutes`,
    '',
    kit.summary,
    '',
    `START HERE: ${kit.deepLink}`,
    '',
    '=================================================================',
    'WALKTHROUGH',
    '=================================================================',
    '',
    ...kit.steps.map((s) => `${s.number}. ${s.title}\n   ${s.detail}\n`),
    '',
    '=================================================================',
    'FILES IN THIS BUNDLE',
    '=================================================================',
    '',
    ...kit.files.map((f) => `- ${f.name}  (${f.format.toUpperCase()}) — ${f.description}`),
    '',
    'Once live, return to Penworth → Publish → paste the URL so we can track it.',
  ];
  bundle.file('README.txt', readmeLines.join('\n'));

  const zipBuf = await bundle.generateAsync({ type: 'nodebuffer' });

  return new NextResponse(new Uint8Array(zipBuf), {
    headers: {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${platformSlug}-publish-kit.zip"`,
    },
  });
}

/**
 * Minimal DOCX builder. Same OOXML shape as /api/export, kept local so this
 * route stays self-contained.
 */
async function buildSimpleDocx(
  title: string,
  author: string,
  chapters: Array<{ title: string; content: string; order_index: number }>,
): Promise<Buffer> {
  const zip = new JSZip();

  zip.file(
    '[Content_Types].xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
</Types>`,
  );

  zip.file(
    '_rels/.rels',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>`,
  );

  const paragraphs: string[] = [];
  paragraphs.push(
    `<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:rPr><w:sz w:val="56"/><w:b/></w:rPr><w:t>${esc(title)}</w:t></w:r></w:p>`,
  );
  paragraphs.push(
    `<w:p><w:r><w:rPr><w:sz w:val="28"/><w:i/></w:rPr><w:t>by ${esc(author)}</w:t></w:r></w:p>`,
  );
  paragraphs.push(`<w:p><w:r><w:br w:type="page"/></w:r></w:p>`);

  const sorted = [...chapters].sort((a, b) => a.order_index - b.order_index);
  for (const ch of sorted) {
    paragraphs.push(
      `<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:rPr><w:sz w:val="36"/><w:b/></w:rPr><w:t>${esc(ch.title)}</w:t></w:r></w:p>`,
    );
    const paras = (ch.content || '').split(/\n\n+/);
    for (const p of paras) {
      if (!p.trim()) continue;
      paragraphs.push(`<w:p><w:r><w:t xml:space="preserve">${esc(p)}</w:t></w:r></w:p>`);
    }
    paragraphs.push(`<w:p><w:r><w:br w:type="page"/></w:r></w:p>`);
  }

  zip.file(
    'word/document.xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${paragraphs.join('\n')}
  </w:body>
</w:document>`,
  );

  return await zip.generateAsync({ type: 'nodebuffer' });
}

function esc(s: string): string {
  return (s || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}
